### ISSUE TITLE
The button of update the layer metadata is broken

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#295] opened 2018-03-04 14:25 UTC
![3](https://user-images.githubusercontent.com/33817803/36946657-e282936c-1ffa-11e8-8105-cdc9e711a126.jpg)

**Comment by capooti** [comment] 2018-03-05 16:37
Hi @lannio 
I can't reproduce this in the demo site, try here for example:
http://128.31.22.73/layers/geonode:zip_codes_2015_zip_s9i/metadata

did you make any customisation?
Apparently the error is raised because there isn't a category set for the layer.

**Comment by capooti** [comment] 2018-03-08 16:42
@lannio I am closing this as I am assuming this is caused by your customization or configuration. Please let me know if you think my assumption is wrong.

**Closed by capooti** 2018-03-08 16:42 UTC
Labels: cannot reproduce
